SELECT 
    A.SHIPMENT_ID, A.FLAVOR, A.TOTAL_ORDER
FROM
    FIRST_HALF A, ICECREAM_INFO B
WHERE
    1=1 
    AND A.FLAVOR = B.FLAVOR
    AND B.INGREDIENT_TYPE = 'fruit_based'
    AND A.TOTAL_ORDER > 3000
ORDER BY A.TOTAL_ORDER DESC
